FROM docker.io/library/debian:bookworm-slim

ARG pubkey

COPY --chmod=755 entrypoint.sh /entrypoint.sh 
COPY sources.list /etc/apt/sources.list
COPY bashrc /root/.bashrc

RUN rm -rf /etc/apt/sources.list.d/* && \
    apt-get update && apt-get install -y \
    openssh-server \
    vim \
    git \
    curl \
    gcc \
    g++ \
    gdb \
    clangd \
    cmake \
    ninja-build && \
    apt-get clean && \
    rm -rf /var/cache/* && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /usr/share/doc/* && \
    rm -rf /usr/share/man/* && \
    rm -rf /usr/share/info/* && \
    rm -rf /tmp/* && \
    mkdir -m 700 -p /root/.ssh && \
    echo "$pubkey" > /root/.ssh/authorized_keys && \
    chmod 600 /root/.ssh/authorized_keys && \
    mkdir /app

WORKDIR /app
EXPOSE 22

ENTRYPOINT ["/entrypoint.sh"]
